<a href="https://colab.research.google.com/github/JoseSergio414/Projeto-Integrador-II/blob/main/PROJETOII_dados_finais_imp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Cadeia Automotiva dados finais importação

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive

In [ ]:
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
origem = '/content/drive/MyDrive/Data/COMEXSTAT/'

In [ ]:
arquivo_1 = origem + 'imp_final_I.csv'
arquivo_2 = origem + 'imp_final_II.csv'
arquivo_3 = origem + 'imp_final_III.csv'

In [ ]:
imp21_22 = pd.read_csv(arquivo_1,low_memory=False,sep=',',encoding='UTF-8')
imp23_24 = pd.read_csv(arquivo_2,low_memory=False,sep=',',encoding='UTF-8')
imp25_26 = pd.read_csv(arquivo_3,low_memory=False,sep=',',encoding='UTF-8')

In [ ]:
dado_imp_final = pd.concat([imp21_22,imp23_24,imp25_26], ignore_index=True)
dado_imp_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8581660 entries, 0 to 8581659
Data columns (total 11 columns):
 #   Column      Dtype
---  ------      -----
 0   CO_ANO      int64
 1   CO_MES      int64
 2   CO_PAIS     int64
 3   SG_UF_MUN   object
 4   CO_MUN      int64
 5   KG_LIQUIDO  int64
 6   VL_FOB      int64
 7   CO_SH4      int64
 8   NO_SH4_POR  object
 9   NO_MUN_MIN  object
 10  NO_PAIS     object
dtypes: int64(7), object(4)
memory usage: 720.2+ MB

In [ ]:
dado_imp_final.head(5)

,CO_ANO,CO_MES,CO_PAIS,SG_UF_MUN,CO_MUN,KG_LIQUIDO,VL_FOB,CO_SH4,NO_SH4_POR,NO_MUN_MIN,NO_PAIS
0,2021,7,23,SP,3416200,3668,11688,4115,Couro reconstituído à base de couro ou de fibr...,Franca,Alemanha
1,2021,4,160,SP,3424709,1,3685,8525,Aparelhos emissores (transmissores) para radio...,Jaguariúna,China
2,2021,7,160,SP,3409205,5043,45918,8302,"Guarnições, ferragens e artigos semelhantes, d...",Cajamar,China
3,2021,1,249,SP,3420509,10417,207124,4009,"Tubos de borracha vulcanizada não endurecida, ...",Indaiatuba,Estados Unidos
4,2021,11,160,SP,3450308,306224,3298907,8536,"Aparelhos para interrupção, seccionamento, pro...",São Paulo,China

In [ ]:
dado_imp_final.tail(5)

,CO_ANO,CO_MES,CO_PAIS,SG_UF_MUN,CO_MUN,KG_LIQUIDO,VL_FOB,CO_SH4,NO_SH4_POR,NO_MUN_MIN,NO_PAIS
8581655,2026,2,351,SC,4208906,1412,202140,8537,"Quadros, painéis, consolas, cabinas, armários ...",Jaraguá do Sul,Hong Kong
8581656,2026,2,72,GO,5303203,0,217,8536,"Aparelhos para interrupção, seccionamento, pro...",Barro Alto,Áustria
8581657,2026,2,603,BA,2905701,3,1143,8544,"Fios, cabos (incluídos os cabos coaxiais) e ou...",Camaçari,Polônia
8581658,2026,1,81,SC,4205407,15261,76679,6110,"Camisolas e pulôveres, cardigans, coletes e ar...",Florianópolis,Bangladesh
8581659,2026,1,351,SP,3425904,419,6861,6601,"Guarda-chuvas, sombrinhas e guarda-sóis (inclu...",Jundiaí,Hong Kong

In [ ]:
print(dado_imp_final.columns)

Index(['CO_ANO', 'CO_MES', 'CO_PAIS', 'SG_UF_MUN', 'CO_MUN', 'KG_LIQUIDO',
       'VL_FOB', 'CO_SH4', 'NO_SH4_POR', 'NO_MUN_MIN', 'NO_PAIS'],
      dtype='object')

In [ ]:
dado_imp_final.to_csv(origem+'dado_imp_final.csv',index=False)