<a href="https://colab.research.google.com/github/JoseSergio414/Projeto-Integrador-II/blob/main/PROJETOII_dados_finais_exp_imp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Cadeia Automotiva dados finais exportação e importação

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive

In [ ]:
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
origem = '/content/drive/MyDrive/Data/COMEXSTAT/'

In [ ]:
arquivo_1 = origem + 'dado_exp_final.csv'
arquivo_2 = origem + 'dado_imp_final.csv'

In [ ]:
expfinal = pd.read_csv(arquivo_1,low_memory=False,sep=',',encoding='UTF-8')
impfinal = pd.read_csv(arquivo_2,low_memory=False,sep=',',encoding='UTF-8')

In [ ]:
dado_final = pd.concat([expfinal,impfinal], ignore_index=True)
dado_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14393339 entries, 0 to 14393338
Data columns (total 13 columns):
 #   Column           Dtype
---  ------           -----
 0   CO_ANO           int64
 1   CO_MES           int64
 2   CO_PAIS          int64
 3   SG_UF_MUN        object
 4   CO_MUN           int64
 5   TOTAL KGL EXP.   float64
 6   TOTAL EXPORTADO  float64
 7   CO_SH4           int64
 8   NO_SH4_POR       object
 9   NO_MUN_MIN       object
 10  NO_PAIS          object
 11  TOTAL KGL IMP.   float64
 12  TOTAL IMPORTADO  float64
dtypes: float64(4), int64(5), object(4)
memory usage: 1.4+ GB

In [ ]:
dado_final.head(5)

,CO_ANO,CO_MES,CO_PAIS,SG_UF_MUN,CO_MUN,TOTAL KGL EXP.,TOTAL EXPORTADO,CO_SH4,NO_SH4_POR,NO_MUN_MIN,NO_PAIS,TOTAL KGL IMP.,TOTAL IMPORTADO
0,2021,3,493,SP,3434401,966.0,7788.0,3305,Preparações capilares,Osasco,México,NaN,NaN
1,2021,7,386,SP,3409502,1.0,1544.0,8419,"Aparelhos e dispositivos, mesmo aquecidos elec...",Campinas,Itália,NaN,NaN
2,2021,12,63,PR,4106902,73.0,907.0,8511,Aparelhos e dispositivos elétricos de ignição ...,Curitiba,Argentina,NaN,NaN
3,2021,7,586,SC,4202909,75.0,3942.0,6204,"Fatos de saia-casaco, conjuntos, casacos, vest...",Brusque,Paraguai,NaN,NaN
4,2021,8,63,SP,3440002,6949.0,29604.0,8708,Partes e acessórios dos veículos automóveis da...,Pompéia,Argentina,NaN,NaN

In [ ]:
dado_final.tail(5)

,CO_ANO,CO_MES,CO_PAIS,SG_UF_MUN,CO_MUN,TOTAL KGL EXP.,TOTAL EXPORTADO,CO_SH4,NO_SH4_POR,NO_MUN_MIN,NO_PAIS,TOTAL KGL IMP.,TOTAL IMPORTADO
14393334,2026,2,351,SC,4208906,NaN,NaN,8537,"Quadros, painéis, consolas, cabinas, armários ...",Jaraguá do Sul,Hong Kong,1412.0,202140.0
14393335,2026,2,72,GO,5303203,NaN,NaN,8536,"Aparelhos para interrupção, seccionamento, pro...",Barro Alto,Áustria,0.0,217.0
14393336,2026,2,603,BA,2905701,NaN,NaN,8544,"Fios, cabos (incluídos os cabos coaxiais) e ou...",Camaçari,Polônia,3.0,1143.0
14393337,2026,1,81,SC,4205407,NaN,NaN,6110,"Camisolas e pulôveres, cardigans, coletes e ar...",Florianópolis,Bangladesh,15261.0,76679.0
14393338,2026,1,351,SP,3425904,NaN,NaN,6601,"Guarda-chuvas, sombrinhas e guarda-sóis (inclu...",Jundiaí,Hong Kong,419.0,6861.0

In [ ]:
float_cols_to_convert = ['TOTAL KGL EXP.', 'TOTAL EXPORTADO', 'TOTAL KGL IMP.', 'TOTAL IMPORTADO']

for col in float_cols_to_convert:
    dado_final[col] = dado_final[col].fillna(0).astype(int)

print("Info after converting specified float columns to integer:")
dado_final.info()

print("\nHead of dado_final after conversion:")
print(dado_final.head(5))

print("\nTail of dado_final after conversion:")
print(dado_final.tail(5))

# Save the modified DataFrame
dado_final.to_csv(origem + 'dado_final.csv', index=False)
print(f"\nModified DataFrame saved to {origem + 'dado_final.csv'}")

Info after converting specified float columns to integer:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14393339 entries, 0 to 14393338
Data columns (total 13 columns):
 #   Column           Dtype
---  ------           -----
 0   CO_ANO           int64
 1   CO_MES           int64
 2   CO_PAIS          int64
 3   SG_UF_MUN        object
 4   CO_MUN           int64
 5   TOTAL KGL EXP.   int64
 6   TOTAL EXPORTADO  int64
 7   CO_SH4           int64
 8   NO_SH4_POR       object
 9   NO_MUN_MIN       object
 10  NO_PAIS          object
 11  TOTAL KGL IMP.   int64
 12  TOTAL IMPORTADO  int64
dtypes: int64(9), object(4)
memory usage: 1.4+ GB

Head of dado_final after conversion:
   CO_ANO  CO_MES  CO_PAIS SG_UF_MUN   CO_MUN  TOTAL KGL EXP.  \
0    2021       3      493        SP  3434401             966
1    2021       7      386        SP  3409502               1
2    2021      12       63        PR  4106902              73
3    2021       7      586        SC  4202909              75
4    2021       8       63        SP  3440002            6949

   TOTAL EXPORTADO  CO_SH4                                         NO_SH4_POR  \
0             7788    3305                              Preparações capilares
1             1544    8419  Aparelhos e dispositivos, mesmo aquecidos elec...
2              907    8511  Aparelhos e dispositivos elétricos de ignição ...
3             3942    6204  Fatos de saia-casaco, conjuntos, casacos, vest...
4            29604    8708  Partes e acessórios dos veículos automóveis da...

  NO_MUN_MIN    NO_PAIS  TOTAL KGL IMP.  TOTAL IMPORTADO
0     Osasco     México               0                0
1   Campinas     Itália               0                0
2   Curitiba  Argentina               0                0
3    Brusque   Paraguai               0                0
4    Pompéia  Argentina               0                0

Tail of dado_final after conversion:
          CO_ANO  CO_MES  CO_PAIS SG_UF_MUN   CO_MUN  TOTAL KGL EXP.  \
14393334    2026       2      351        SC  4208906               0
14393335    2026       2       72        GO  5303203               0
14393336    2026       2      603        BA  2905701               0
14393337    2026       1       81        SC  4205407               0
14393338    2026       1      351        SP  3425904               0

          TOTAL EXPORTADO  CO_SH4  \
14393334                0    8537
14393335                0    8536
14393336                0    8544
14393337                0    6110
14393338                0    6601

                                                 NO_SH4_POR      NO_MUN_MIN  \
14393334  Quadros, painéis, consolas, cabinas, armários ...  Jaraguá do Sul
14393335  Aparelhos para interrupção, seccionamento, pro...      Barro Alto
14393336  Fios, cabos (incluídos os cabos coaxiais) e ou...        Camaçari
14393337  Camisolas e pulôveres, cardigans, coletes e ar...   Florianópolis
14393338  Guarda-chuvas, sombrinhas e guarda-sóis (inclu...         Jundiaí

             NO_PAIS  TOTAL KGL IMP.  TOTAL IMPORTADO
14393334   Hong Kong            1412           202140
14393335     Áustria               0              217
14393336     Polônia               3             1143
14393337  Bangladesh           15261            76679
14393338   Hong Kong             419             6861

Modified DataFrame saved to /content/drive/MyDrive/Data/COMEXSTAT/dado_final.csv

In [ ]:
dado_final.head(5)

,CO_ANO,CO_MES,CO_PAIS,SG_UF_MUN,CO_MUN,TOTAL KGL EXP.,TOTAL EXPORTADO,CO_SH4,NO_SH4_POR,NO_MUN_MIN,NO_PAIS,TOTAL KGL IMP.,TOTAL IMPORTADO
0,2021,3,493,SP,3434401,966,7788,3305,Preparações capilares,Osasco,México,0,0
1,2021,7,386,SP,3409502,1,1544,8419,"Aparelhos e dispositivos, mesmo aquecidos elec...",Campinas,Itália,0,0
2,2021,12,63,PR,4106902,73,907,8511,Aparelhos e dispositivos elétricos de ignição ...,Curitiba,Argentina,0,0
3,2021,7,586,SC,4202909,75,3942,6204,"Fatos de saia-casaco, conjuntos, casacos, vest...",Brusque,Paraguai,0,0
4,2021,8,63,SP,3440002,6949,29604,8708,Partes e acessórios dos veículos automóveis da...,Pompéia,Argentina,0,0

In [ ]:
dado_final.tail(5)

,CO_ANO,CO_MES,CO_PAIS,SG_UF_MUN,CO_MUN,TOTAL KGL EXP.,TOTAL EXPORTADO,CO_SH4,NO_SH4_POR,NO_MUN_MIN,NO_PAIS,TOTAL KGL IMP.,TOTAL IMPORTADO
14393334,2026,2,351,SC,4208906,0,0,8537,"Quadros, painéis, consolas, cabinas, armários ...",Jaraguá do Sul,Hong Kong,1412,202140
14393335,2026,2,72,GO,5303203,0,0,8536,"Aparelhos para interrupção, seccionamento, pro...",Barro Alto,Áustria,0,217
14393336,2026,2,603,BA,2905701,0,0,8544,"Fios, cabos (incluídos os cabos coaxiais) e ou...",Camaçari,Polônia,3,1143
14393337,2026,1,81,SC,4205407,0,0,6110,"Camisolas e pulôveres, cardigans, coletes e ar...",Florianópolis,Bangladesh,15261,76679
14393338,2026,1,351,SP,3425904,0,0,6601,"Guarda-chuvas, sombrinhas e guarda-sóis (inclu...",Jundiaí,Hong Kong,419,6861

In [ ]:
print(dado_final.columns)

Index(['CO_ANO', 'CO_MES', 'CO_PAIS', 'SG_UF_MUN', 'CO_MUN', 'TOTAL KGL EXP.',
       'TOTAL EXPORTADO', 'CO_SH4', 'NO_SH4_POR', 'NO_MUN_MIN', 'NO_PAIS',
       'TOTAL KGL IMP.', 'TOTAL IMPORTADO'],
      dtype='object')

In [ ]:
dado_final.to_csv(origem+'dado_final.csv',index=False)