<a href="https://colab.research.google.com/github/JoseSergio414/Projeto-Integrador-II/blob/main/PROJETOII_exporta%C3%A7%C3%A3o_I.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Cadeia Automotiva exportação I parte

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive

In [ ]:
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
origem = '/content/drive/MyDrive/Data/COMEXSTAT/'

In [ ]:
arquivo_1 = origem + 'EXP_2021_MUN.csv'
arquivo_2 = origem + 'EXP_2022_MUN.csv'
pais = origem + 'PAIS.csv'
uf_mun =origem + 'UF_MUN.csv'
ncm_sh = origem + 'NCM_SH.csv'

In [ ]:
exp21 = pd.read_csv(arquivo_1,low_memory=False,sep=';',encoding='UTF-8')
exp22 = pd.read_csv(arquivo_2,low_memory=False,sep=';',encoding='UTF-8')
exppais = pd.read_csv(pais,low_memory=False,sep=';',encoding='latin1')
expufmun = pd.read_csv(uf_mun,low_memory=False,sep=';',encoding='latin1')
expsh = pd.read_csv(ncm_sh,low_memory=False,sep=';',encoding='latin1')

In [ ]:
exp_final = pd.concat([exp21,exp22], ignore_index=True)
exp_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2162653 entries, 0 to 2162652
Data columns (total 8 columns):
 #   Column      Dtype
---  ------      -----
 0   CO_ANO      int64
 1   CO_MES      int64
 2   SH4         int64
 3   CO_PAIS     int64
 4   SG_UF_MUN   object
 5   CO_MUN      int64
 6   KG_LIQUIDO  int64
 7   VL_FOB      int64
dtypes: int64(7), object(1)
memory usage: 132.0+ MB

In [ ]:
exp_final.head(5)

   CO_ANO  CO_MES   SH4  CO_PAIS SG_UF_MUN   CO_MUN  KG_LIQUIDO  VL_FOB
0    2021       3  3305      493        SP  3434401         966    7788
1    2021       7  8419      386        SP  3409502           1    1544
2    2021      12  8511       63        PR  4106902          73     907
3    2021       7  6204      586        SC  4202909          75    3942
4    2021       8  8708       63        SP  3440002        6949   29604

In [ ]:
exp_final.tail(5)

         CO_ANO  CO_MES   SH4  CO_PAIS SG_UF_MUN   CO_MUN  KG_LIQUIDO  VL_FOB
2162648    2022       9  2201      445        SP  3448500        1260     328
2162649    2022       7  9603      586        RS  4304804          24     350
2162650    2022       9  8527      239        PR  4120804         234   34731
2162651    2022       1   203      767        PA  1506807          30     226
2162652    2022       1  8527       63        SP  3452403           7    2246

In [ ]:
exp_final = exp_final.merge(expsh[['CO_SH4','NO_SH4_POR']], left_on='SH4', right_on='CO_SH4', how='left')

In [ ]:
exp_final = exp_final.merge(expufmun[['CO_MUN_GEO','NO_MUN_MIN']],left_on='CO_MUN', right_on='CO_MUN_GEO', how='left')

In [ ]:
exp_final = exp_final.merge(exppais[['CO_PAIS','NO_PAIS']],on='CO_PAIS',how='left')

In [ ]:
exp_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17167559 entries, 0 to 17167558
Data columns (total 13 columns):
 #   Column      Dtype
---  ------      -----
 0   CO_ANO      int64
 1   CO_MES      int64
 2   SH4         int64
 3   CO_PAIS     int64
 4   SG_UF_MUN   object
 5   CO_MUN      int64
 6   KG_LIQUIDO  int64
 7   VL_FOB      int64
 8   CO_SH4      int64
 9   NO_SH4_POR  object
 10  CO_MUN_GEO  int64
 11  NO_MUN_MIN  object
 12  NO_PAIS     object
dtypes: int64(9), object(4)
memory usage: 1.7+ GB

In [ ]:
exp_final.head(5)

,CO_ANO,CO_MES,SH4,CO_PAIS,SG_UF_MUN,CO_MUN,KG_LIQUIDO,VL_FOB,CO_SH4,NO_SH4_POR,CO_MUN_GEO,NO_MUN_MIN,NO_PAIS
0,2021,3,3305,493,SP,3434401,966,7788,3305,Preparações capilares,3434401,Osasco,México
1,2021,3,3305,493,SP,3434401,966,7788,3305,Preparações capilares,3434401,Osasco,México
2,2021,3,3305,493,SP,3434401,966,7788,3305,Preparações capilares,3434401,Osasco,México
3,2021,3,3305,493,SP,3434401,966,7788,3305,Preparações capilares,3434401,Osasco,México
4,2021,7,8419,386,SP,3409502,1,1544,8419,"Aparelhos e dispositivos, mesmo aquecidos elec...",3409502,Campinas,Itália

In [ ]:
exp_final.tail(5)

,CO_ANO,CO_MES,SH4,CO_PAIS,SG_UF_MUN,CO_MUN,KG_LIQUIDO,VL_FOB,CO_SH4,NO_SH4_POR,CO_MUN_GEO,NO_MUN_MIN,NO_PAIS
17167554,2022,1,8527,63,SP,3452403,7,2246,8527,"Aparelhos receptores para radiotelefonia, radi...",3452403,Sumaré,Argentina
17167555,2022,1,8527,63,SP,3452403,7,2246,8527,"Aparelhos receptores para radiotelefonia, radi...",3452403,Sumaré,Argentina
17167556,2022,1,8527,63,SP,3452403,7,2246,8527,"Aparelhos receptores para radiotelefonia, radi...",3452403,Sumaré,Argentina
17167557,2022,1,8527,63,SP,3452403,7,2246,8527,"Aparelhos receptores para radiotelefonia, radi...",3452403,Sumaré,Argentina
17167558,2022,1,8527,63,SP,3452403,7,2246,8527,"Aparelhos receptores para radiotelefonia, radi...",3452403,Sumaré,Argentina

In [ ]:
exp_final = exp_final.drop('SH4', axis=1)

In [ ]:
exp_final = exp_final.drop('CO_MUN_GEO', axis=1)

In [ ]:
exp_final.head(5)

,CO_ANO,CO_MES,CO_PAIS,SG_UF_MUN,CO_MUN,KG_LIQUIDO,VL_FOB,CO_SH4,NO_SH4_POR,NO_MUN_MIN,NO_PAIS
0,2021,3,493,SP,3434401,966,7788,3305,Preparações capilares,Osasco,México
1,2021,3,493,SP,3434401,966,7788,3305,Preparações capilares,Osasco,México
2,2021,3,493,SP,3434401,966,7788,3305,Preparações capilares,Osasco,México
3,2021,3,493,SP,3434401,966,7788,3305,Preparações capilares,Osasco,México
4,2021,7,386,SP,3409502,1,1544,8419,"Aparelhos e dispositivos, mesmo aquecidos elec...",Campinas,Itália

In [ ]:
print(f"Shape of exp_final before dropping duplicates: {exp_final.shape}")
exp_final = exp_final.drop_duplicates()
print(f"Shape of exp_final after dropping duplicates: {exp_final.shape}")

Shape of exp_final before dropping duplicates: (17167559, 11)
Shape of exp_final after dropping duplicates: (2162653, 11)

In [ ]:
exp_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2162653 entries, 0 to 17167547
Data columns (total 11 columns):
 #   Column      Dtype
---  ------      -----
 0   CO_ANO      int64
 1   CO_MES      int64
 2   CO_PAIS     int64
 3   SG_UF_MUN   object
 4   CO_MUN      int64
 5   KG_LIQUIDO  int64
 6   VL_FOB      int64
 7   CO_SH4      int64
 8   NO_SH4_POR  object
 9   NO_MUN_MIN  object
 10  NO_PAIS     object
dtypes: int64(7), object(4)
memory usage: 198.0+ MB

In [ ]:
print(exp_final.columns)

Index(['CO_ANO', 'CO_MES', 'CO_PAIS', 'SG_UF_MUN', 'CO_MUN', 'KG_LIQUIDO',
       'VL_FOB', 'CO_SH4', 'NO_SH4_POR', 'NO_MUN_MIN', 'NO_PAIS'],
      dtype='object')

In [ ]:
exp_final.to_csv(origem+'exp_final.csv',index=False)