<a href="https://colab.research.google.com/github/JoseSergio414/Projeto-Integrador-II/blob/main/PROJETOII_importa%C3%A7%C3%A3o_II.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Cadeia Automotiva importação II parte

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive

In [ ]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
origem = '/content/drive/MyDrive/Data/COMEXSTAT/'

In [ ]:
arquivo_1 = origem + 'IMP_2023_MUN.csv'
arquivo_2 = origem + 'IMP_2024_MUN.csv'
pais = origem + 'PAIS.csv'
uf_mun =origem + 'UF_MUN.csv'
ncm_sh = origem + 'NCM_SH.csv'

In [ ]:
imp23 = pd.read_csv(arquivo_1,low_memory=False,sep=';',encoding='UTF-8')
imp24 = pd.read_csv(arquivo_2,low_memory=False,sep=';',encoding='UTF-8')
imppais = pd.read_csv(pais,low_memory=False,sep=';',encoding='latin1')
impufmun = pd.read_csv(uf_mun,low_memory=False,sep=';',encoding='latin1')
impsh = pd.read_csv(ncm_sh,low_memory=False,sep=';',encoding='latin1')

In [ ]:
imp_final = pd.concat([imp23,imp24], ignore_index=True)
imp_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3362514 entries, 0 to 3362513
Data columns (total 8 columns):
 #   Column      Dtype
---  ------      -----
 0   CO_ANO      int64
 1   CO_MES      int64
 2   SH4         int64
 3   CO_PAIS     int64
 4   SG_UF_MUN   object
 5   CO_MUN      int64
 6   KG_LIQUIDO  int64
 7   VL_FOB      int64
dtypes: int64(7), object(1)
memory usage: 205.2+ MB

In [ ]:
imp_final.head(5)

   CO_ANO  CO_MES   SH4  CO_PAIS SG_UF_MUN   CO_MUN  KG_LIQUIDO    VL_FOB
0    2023       5  3104      676        GO  5305109    35717261  15254781
1    2023      12  6104      858        SP  3415004        8189    255925
2    2023       2  8543      399        SP  3419071          19     12156
3    2023       4  7326      249        SP  3413504          18      3859
4    2023       6  8542      161        SC  4209102         202     51196

In [ ]:
imp_final.tail(5)

         CO_ANO  CO_MES   SH4  CO_PAIS SG_UF_MUN   CO_MUN  KG_LIQUIDO  VL_FOB
3362509    2024       6  3808       23        PR  4103701       64944  156566
3362510    2024      10  8481      607        SP  3438709           2     154
3362511    2024       8  8708      737        SP  3450308           0      25
3362512    2024       2  8483      160        SP  3430508        1227   17798
3362513    2024       9  9017      767        RS  4314902           1     238

In [ ]:
imp_final = imp_final.merge(impsh[['CO_SH4','NO_SH4_POR']], left_on='SH4', right_on='CO_SH4', how='left')

In [ ]:
imp_final = imp_final.merge(impufmun[['CO_MUN_GEO','NO_MUN_MIN']],left_on='CO_MUN', right_on='CO_MUN_GEO', how='left')

In [ ]:
imp_final = imp_final.merge(imppais[['CO_PAIS','NO_PAIS']],on='CO_PAIS',how='left')

In [ ]:
imp_final.info()

In [ ]:
imp_final.head(5)

,CO_ANO,CO_MES,SH4,CO_PAIS,SG_UF_MUN,CO_MUN,KG_LIQUIDO,VL_FOB,CO_SH4,NO_SH4_POR,CO_MUN_GEO,NO_MUN_MIN,NO_PAIS
0,2023,5,3104,676,GO,5305109,35717261,15254781,3104,"Adubos (fertilizantes) minerais ou químicos, p...",5305109,Catalão,Rússia
1,2023,5,3104,676,GO,5305109,35717261,15254781,3104,"Adubos (fertilizantes) minerais ou químicos, p...",5305109,Catalão,Rússia
2,2023,5,3104,676,GO,5305109,35717261,15254781,3104,"Adubos (fertilizantes) minerais ou químicos, p...",5305109,Catalão,Rússia
3,2023,5,3104,676,GO,5305109,35717261,15254781,3104,"Adubos (fertilizantes) minerais ou químicos, p...",5305109,Catalão,Rússia
4,2023,12,6104,858,SP,3415004,8189,255925,6104,"Fatos de saia-casaco, conjuntos, casacos, vest...",3415004,Embu,Vietnã

In [ ]:
imp_final.tail(5)

,CO_ANO,CO_MES,SH4,CO_PAIS,SG_UF_MUN,CO_MUN,KG_LIQUIDO,VL_FOB,CO_SH4,NO_SH4_POR,CO_MUN_GEO,NO_MUN_MIN,NO_PAIS
27804216,2024,9,9017,767,RS,4314902,1,238,9017,"Instrumentos de desenho, de traçado ou de cálc...",4314902,Porto Alegre,Suíça
27804217,2024,9,9017,767,RS,4314902,1,238,9017,"Instrumentos de desenho, de traçado ou de cálc...",4314902,Porto Alegre,Suíça
27804218,2024,9,9017,767,RS,4314902,1,238,9017,"Instrumentos de desenho, de traçado ou de cálc...",4314902,Porto Alegre,Suíça
27804219,2024,9,9017,767,RS,4314902,1,238,9017,"Instrumentos de desenho, de traçado ou de cálc...",4314902,Porto Alegre,Suíça
27804220,2024,9,9017,767,RS,4314902,1,238,9017,"Instrumentos de desenho, de traçado ou de cálc...",4314902,Porto Alegre,Suíça

In [ ]:
imp_final = imp_final.drop('SH4', axis=1)

In [ ]:
imp_final = imp_final.drop('CO_MUN_GEO', axis=1)

In [ ]:
imp_final.head(5)

,CO_ANO,CO_MES,CO_PAIS,SG_UF_MUN,CO_MUN,KG_LIQUIDO,VL_FOB,CO_SH4,NO_SH4_POR,NO_MUN_MIN,NO_PAIS
0,2023,5,676,GO,5305109,35717261,15254781,3104,"Adubos (fertilizantes) minerais ou químicos, p...",Catalão,Rússia
1,2023,5,676,GO,5305109,35717261,15254781,3104,"Adubos (fertilizantes) minerais ou químicos, p...",Catalão,Rússia
2,2023,5,676,GO,5305109,35717261,15254781,3104,"Adubos (fertilizantes) minerais ou químicos, p...",Catalão,Rússia
3,2023,5,676,GO,5305109,35717261,15254781,3104,"Adubos (fertilizantes) minerais ou químicos, p...",Catalão,Rússia
4,2023,12,858,SP,3415004,8189,255925,6104,"Fatos de saia-casaco, conjuntos, casacos, vest...",Embu,Vietnã

In [ ]:
print(f"Shape of imp_final before dropping duplicates: {imp_final.shape}")
imp_final = imp_final.drop_duplicates()
print(f"Shape of imp_final after dropping duplicates: {imp_final.shape}")

Shape of imp_final before dropping duplicates: (27804221, 11)
Shape of imp_final after dropping duplicates: (3362514, 11)

In [ ]:
imp_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3362514 entries, 0 to 27804216
Data columns (total 11 columns):
 #   Column      Dtype
---  ------      -----
 0   CO_ANO      int64
 1   CO_MES      int64
 2   CO_PAIS     int64
 3   SG_UF_MUN   object
 4   CO_MUN      int64
 5   KG_LIQUIDO  int64
 6   VL_FOB      int64
 7   CO_SH4      int64
 8   NO_SH4_POR  object
 9   NO_MUN_MIN  object
 10  NO_PAIS     object
dtypes: int64(7), object(4)
memory usage: 307.8+ MB

In [ ]:
print(imp_final.columns)

Index(['CO_ANO', 'CO_MES', 'CO_PAIS', 'SG_UF_MUN', 'CO_MUN', 'KG_LIQUIDO',
       'VL_FOB', 'CO_SH4', 'NO_SH4_POR', 'NO_MUN_MIN', 'NO_PAIS'],
      dtype='object')

In [ ]:
imp_final.to_csv(origem+'imp_final.csv',index=False)