<a href="https://colab.research.google.com/github/JoseSergio414/Projeto-Integrador-II/blob/main/PROJETOII_importa%C3%A7%C3%A3o_III.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Cadeia Automotiva importação III parte

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive

In [ ]:
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
origem = '/content/drive/MyDrive/Data/COMEXSTAT/'

In [ ]:
arquivo_1 = origem + 'IMP_2025_MUN.csv'
arquivo_2 = origem + 'IMP_2026_MUN.csv'
pais = origem + 'PAIS.csv'
uf_mun =origem + 'UF_MUN.csv'
ncm_sh = origem + 'NCM_SH.csv'

In [ ]:
imp25 = pd.read_csv(arquivo_1,low_memory=False,sep=';',encoding='UTF-8')
imp26 = pd.read_csv(arquivo_2,low_memory=False,sep=';',encoding='UTF-8')
imppais = pd.read_csv(pais,low_memory=False,sep=';',encoding='latin1')
impufmun = pd.read_csv(uf_mun,low_memory=False,sep=';',encoding='latin1')
impsh = pd.read_csv(ncm_sh,low_memory=False,sep=';',encoding='latin1')

In [ ]:
imp_final = pd.concat([imp25,imp26], ignore_index=True)
imp_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2084571 entries, 0 to 2084570
Data columns (total 8 columns):
 #   Column      Dtype
---  ------      -----
 0   CO_ANO      int64
 1   CO_MES      int64
 2   SH4         int64
 3   CO_PAIS     int64
 4   SG_UF_MUN   object
 5   CO_MUN      int64
 6   KG_LIQUIDO  int64
 7   VL_FOB      int64
dtypes: int64(7), object(1)
memory usage: 127.2+ MB

In [ ]:
imp_final.head(5)

   CO_ANO  CO_MES   SH4  CO_PAIS SG_UF_MUN   CO_MUN  KG_LIQUIDO   VL_FOB
0    2025       8  7318       23        MG  3105905          97     6961
1    2025       3  3926      827        RN  2403251           0        0
2    2025       4  3102      528        PR  4118204    12158590  4511134
3    2025      11  8708      249        RS  4304606          16      340
4    2025       8  7318       23        SP  3452205       32965   422234

In [ ]:
imp_final.tail(5)

         CO_ANO  CO_MES   SH4  CO_PAIS SG_UF_MUN   CO_MUN  KG_LIQUIDO  VL_FOB
2084566    2026       2  8537      351        SC  4208906        1412  202140
2084567    2026       2  8536       72        GO  5303203           0     217
2084568    2026       2  8544      603        BA  2905701           3    1143
2084569    2026       1  6110       81        SC  4205407       15261   76679
2084570    2026       1  6601      351        SP  3425904         419    6861

In [ ]:
imp_final = imp_final.merge(impsh[['CO_SH4','NO_SH4_POR']], left_on='SH4', right_on='CO_SH4', how='left')

In [ ]:
imp_final = imp_final.merge(impufmun[['CO_MUN_GEO','NO_MUN_MIN']],left_on='CO_MUN', right_on='CO_MUN_GEO', how='left')

In [ ]:
imp_final = imp_final.merge(imppais[['CO_PAIS','NO_PAIS']],on='CO_PAIS',how='left')

In [ ]:
imp_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17171416 entries, 0 to 17171415
Data columns (total 13 columns):
 #   Column      Dtype
---  ------      -----
 0   CO_ANO      int64
 1   CO_MES      int64
 2   SH4         int64
 3   CO_PAIS     int64
 4   SG_UF_MUN   object
 5   CO_MUN      int64
 6   KG_LIQUIDO  int64
 7   VL_FOB      int64
 8   CO_SH4      int64
 9   NO_SH4_POR  object
 10  CO_MUN_GEO  int64
 11  NO_MUN_MIN  object
 12  NO_PAIS     object
dtypes: int64(9), object(4)
memory usage: 1.7+ GB

In [ ]:
imp_final.head(5)

,CO_ANO,CO_MES,SH4,CO_PAIS,SG_UF_MUN,CO_MUN,KG_LIQUIDO,VL_FOB,CO_SH4,NO_SH4_POR,CO_MUN_GEO,NO_MUN_MIN,NO_PAIS
0,2025,8,7318,23,MG,3105905,97,6961,7318,"Parafusos, pernos ou pinos, roscados, porcas, ...",3105905,Barroso,Alemanha
1,2025,8,7318,23,MG,3105905,97,6961,7318,"Parafusos, pernos ou pinos, roscados, porcas, ...",3105905,Barroso,Alemanha
2,2025,8,7318,23,MG,3105905,97,6961,7318,"Parafusos, pernos ou pinos, roscados, porcas, ...",3105905,Barroso,Alemanha
3,2025,8,7318,23,MG,3105905,97,6961,7318,"Parafusos, pernos ou pinos, roscados, porcas, ...",3105905,Barroso,Alemanha
4,2025,8,7318,23,MG,3105905,97,6961,7318,"Parafusos, pernos ou pinos, roscados, porcas, ...",3105905,Barroso,Alemanha

In [ ]:
imp_final.tail(5)

,CO_ANO,CO_MES,SH4,CO_PAIS,SG_UF_MUN,CO_MUN,KG_LIQUIDO,VL_FOB,CO_SH4,NO_SH4_POR,CO_MUN_GEO,NO_MUN_MIN,NO_PAIS
17171411,2026,1,6110,81,SC,4205407,15261,76679,6110,"Camisolas e pulôveres, cardigans, coletes e ar...",4205407,Florianópolis,Bangladesh
17171412,2026,1,6110,81,SC,4205407,15261,76679,6110,"Camisolas e pulôveres, cardigans, coletes e ar...",4205407,Florianópolis,Bangladesh
17171413,2026,1,6601,351,SP,3425904,419,6861,6601,"Guarda-chuvas, sombrinhas e guarda-sóis (inclu...",3425904,Jundiaí,Hong Kong
17171414,2026,1,6601,351,SP,3425904,419,6861,6601,"Guarda-chuvas, sombrinhas e guarda-sóis (inclu...",3425904,Jundiaí,Hong Kong
17171415,2026,1,6601,351,SP,3425904,419,6861,6601,"Guarda-chuvas, sombrinhas e guarda-sóis (inclu...",3425904,Jundiaí,Hong Kong

In [ ]:
imp_final = imp_final.drop('SH4', axis=1)

In [ ]:
imp_final = imp_final.drop('CO_MUN_GEO', axis=1)

In [ ]:
imp_final.head(5)

,CO_ANO,CO_MES,CO_PAIS,SG_UF_MUN,CO_MUN,KG_LIQUIDO,VL_FOB,CO_SH4,NO_SH4_POR,NO_MUN_MIN,NO_PAIS
0,2025,8,23,MG,3105905,97,6961,7318,"Parafusos, pernos ou pinos, roscados, porcas, ...",Barroso,Alemanha
1,2025,8,23,MG,3105905,97,6961,7318,"Parafusos, pernos ou pinos, roscados, porcas, ...",Barroso,Alemanha
2,2025,8,23,MG,3105905,97,6961,7318,"Parafusos, pernos ou pinos, roscados, porcas, ...",Barroso,Alemanha
3,2025,8,23,MG,3105905,97,6961,7318,"Parafusos, pernos ou pinos, roscados, porcas, ...",Barroso,Alemanha
4,2025,8,23,MG,3105905,97,6961,7318,"Parafusos, pernos ou pinos, roscados, porcas, ...",Barroso,Alemanha

In [ ]:
print(f"Shape of imp_final before dropping duplicates: {imp_final.shape}")
imp_final = imp_final.drop_duplicates()
print(f"Shape of imp_final after dropping duplicates: {imp_final.shape}")

Shape of imp_final before dropping duplicates: (17171416, 11)
Shape of imp_final after dropping duplicates: (2084571, 11)

In [ ]:
imp_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2084571 entries, 0 to 17171413
Data columns (total 11 columns):
 #   Column      Dtype
---  ------      -----
 0   CO_ANO      int64
 1   CO_MES      int64
 2   CO_PAIS     int64
 3   SG_UF_MUN   object
 4   CO_MUN      int64
 5   KG_LIQUIDO  int64
 6   VL_FOB      int64
 7   CO_SH4      int64
 8   NO_SH4_POR  object
 9   NO_MUN_MIN  object
 10  NO_PAIS     object
dtypes: int64(7), object(4)
memory usage: 190.8+ MB

In [ ]:
print(imp_final.columns)

Index(['CO_ANO', 'CO_MES', 'CO_PAIS', 'SG_UF_MUN', 'CO_MUN', 'KG_LIQUIDO',
       'VL_FOB', 'CO_SH4', 'NO_SH4_POR', 'NO_MUN_MIN', 'NO_PAIS'],
      dtype='object')

In [ ]:
imp_final.to_csv(origem+'imp_final.csv',index=False)