<a href="https://colab.research.google.com/github/JoseSergio414/Projeto-Integrador-II/blob/main/PROJETOII_exporta%C3%A7%C3%A3o_II.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Cadeia Automotiva exportação II parte

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive

In [ ]:
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
origem = '/content/drive/MyDrive/Data/COMEXSTAT/'

In [ ]:
arquivo_1 = origem + 'EXP_2023_MUN.csv'
arquivo_2 = origem + 'EXP_2024_MUN.csv'
pais = origem + 'PAIS.csv'
uf_mun =origem + 'UF_MUN.csv'
ncm_sh = origem + 'NCM_SH.csv'

In [ ]:
exp23 = pd.read_csv(arquivo_1,low_memory=False,sep=';',encoding='UTF-8')
exp24 = pd.read_csv(arquivo_2,low_memory=False,sep=';',encoding='UTF-8')
exppais = pd.read_csv(pais,low_memory=False,sep=';',encoding='latin1')
expufmun = pd.read_csv(uf_mun,low_memory=False,sep=';',encoding='latin1')
expsh = pd.read_csv(ncm_sh,low_memory=False,sep=';',encoding='latin1')

In [ ]:
exp_final = pd.concat([exp23,exp24], ignore_index=True)
exp_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2266180 entries, 0 to 2266179
Data columns (total 8 columns):
 #   Column      Dtype
---  ------      -----
 0   CO_ANO      int64
 1   CO_MES      int64
 2   SH4         int64
 3   CO_PAIS     int64
 4   SG_UF_MUN   object
 5   CO_MUN      int64
 6   KG_LIQUIDO  int64
 7   VL_FOB      int64
dtypes: int64(7), object(1)
memory usage: 138.3+ MB

In [ ]:
exp_final.head(5)

   CO_ANO  CO_MES   SH4  CO_PAIS SG_UF_MUN   CO_MUN  KG_LIQUIDO  VL_FOB
0    2023      10  2209      127        BA  2919553          36      53
1    2023      11  4009      493        SP  3456701         473   14008
2    2023      11  8536      365        SP  3438709           2     181
3    2023       8  8512       63        RJ  3304201       15627  239105
4    2023       6  1902      580        PR  4118204         287     368

In [ ]:
exp_final.tail(5)

         CO_ANO  CO_MES   SH4  CO_PAIS SG_UF_MUN   CO_MUN  KG_LIQUIDO  VL_FOB
2266175    2024       8  6206       63        SP  3405500           3      79
2266176    2024       6  3104      494        PR  4115200         197    1200
2266177    2024       3  8205      275        MG  3132404           3    5454
2266178    2024       2  8504      589        SP  3448906           0    2390
2266179    2024      11   406      776        SP  3448500           4      72

In [ ]:
exp_final = exp_final.merge(expsh[['CO_SH4','NO_SH4_POR']], left_on='SH4', right_on='CO_SH4', how='left')

In [ ]:
exp_final = exp_final.merge(expufmun[['CO_MUN_GEO','NO_MUN_MIN']],left_on='CO_MUN', right_on='CO_MUN_GEO', how='left')

In [ ]:
exp_final = exp_final.merge(exppais[['CO_PAIS','NO_PAIS']],on='CO_PAIS',how='left')

In [ ]:
exp_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17886237 entries, 0 to 17886236
Data columns (total 13 columns):
 #   Column      Dtype
---  ------      -----
 0   CO_ANO      int64
 1   CO_MES      int64
 2   SH4         int64
 3   CO_PAIS     int64
 4   SG_UF_MUN   object
 5   CO_MUN      int64
 6   KG_LIQUIDO  int64
 7   VL_FOB      int64
 8   CO_SH4      int64
 9   NO_SH4_POR  object
 10  CO_MUN_GEO  int64
 11  NO_MUN_MIN  object
 12  NO_PAIS     object
dtypes: int64(9), object(4)
memory usage: 1.7+ GB

In [ ]:
exp_final.head(5)

,CO_ANO,CO_MES,SH4,CO_PAIS,SG_UF_MUN,CO_MUN,KG_LIQUIDO,VL_FOB,CO_SH4,NO_SH4_POR,CO_MUN_GEO,NO_MUN_MIN,NO_PAIS
0,2023,10,2209,127,BA,2919553,36,53,2209,Vinagres e seus sucedâneos obtidos a partir do...,2919553,Luís Eduardo Magalhães,Cabo Verde
1,2023,11,4009,493,SP,3456701,473,14008,4009,"Tubos de borracha vulcanizada não endurecida, ...",3456701,Vinhedo,México
2,2023,11,4009,493,SP,3456701,473,14008,4009,"Tubos de borracha vulcanizada não endurecida, ...",3456701,Vinhedo,México
3,2023,11,4009,493,SP,3456701,473,14008,4009,"Tubos de borracha vulcanizada não endurecida, ...",3456701,Vinhedo,México
4,2023,11,4009,493,SP,3456701,473,14008,4009,"Tubos de borracha vulcanizada não endurecida, ...",3456701,Vinhedo,México

In [ ]:
exp_final.tail(5)

,CO_ANO,CO_MES,SH4,CO_PAIS,SG_UF_MUN,CO_MUN,KG_LIQUIDO,VL_FOB,CO_SH4,NO_SH4_POR,CO_MUN_GEO,NO_MUN_MIN,NO_PAIS
17886232,2024,11,406,776,SP,3448500,4,72,406,Queijos e requeijão,3448500,Santos,Tailândia
17886233,2024,11,406,776,SP,3448500,4,72,406,Queijos e requeijão,3448500,Santos,Tailândia
17886234,2024,11,406,776,SP,3448500,4,72,406,Queijos e requeijão,3448500,Santos,Tailândia
17886235,2024,11,406,776,SP,3448500,4,72,406,Queijos e requeijão,3448500,Santos,Tailândia
17886236,2024,11,406,776,SP,3448500,4,72,406,Queijos e requeijão,3448500,Santos,Tailândia

In [ ]:
exp_final = exp_final.drop('SH4', axis=1)

In [ ]:
exp_final = exp_final.drop('CO_MUN_GEO', axis=1)

In [ ]:
exp_final.head(5)

,CO_ANO,CO_MES,CO_PAIS,SG_UF_MUN,CO_MUN,KG_LIQUIDO,VL_FOB,CO_SH4,NO_SH4_POR,NO_MUN_MIN,NO_PAIS
0,2023,10,127,BA,2919553,36,53,2209,Vinagres e seus sucedâneos obtidos a partir do...,Luís Eduardo Magalhães,Cabo Verde
1,2023,11,493,SP,3456701,473,14008,4009,"Tubos de borracha vulcanizada não endurecida, ...",Vinhedo,México
2,2023,11,493,SP,3456701,473,14008,4009,"Tubos de borracha vulcanizada não endurecida, ...",Vinhedo,México
3,2023,11,493,SP,3456701,473,14008,4009,"Tubos de borracha vulcanizada não endurecida, ...",Vinhedo,México
4,2023,11,493,SP,3456701,473,14008,4009,"Tubos de borracha vulcanizada não endurecida, ...",Vinhedo,México

In [ ]:
print(f"Shape of exp_final before dropping duplicates: {exp_final.shape}")
exp_final = exp_final.drop_duplicates()
print(f"Shape of exp_final after dropping duplicates: {exp_final.shape}")

Shape of exp_final before dropping duplicates: (17886237, 11)
Shape of exp_final after dropping duplicates: (2266180, 11)

In [ ]:
exp_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2266180 entries, 0 to 17886232
Data columns (total 11 columns):
 #   Column      Dtype
---  ------      -----
 0   CO_ANO      int64
 1   CO_MES      int64
 2   CO_PAIS     int64
 3   SG_UF_MUN   object
 4   CO_MUN      int64
 5   KG_LIQUIDO  int64
 6   VL_FOB      int64
 7   CO_SH4      int64
 8   NO_SH4_POR  object
 9   NO_MUN_MIN  object
 10  NO_PAIS     object
dtypes: int64(7), object(4)
memory usage: 207.5+ MB

In [ ]:
print(exp_final.columns)

Index(['CO_ANO', 'CO_MES', 'CO_PAIS', 'SG_UF_MUN', 'CO_MUN', 'KG_LIQUIDO',
       'VL_FOB', 'CO_SH4', 'NO_SH4_POR', 'NO_MUN_MIN', 'NO_PAIS'],
      dtype='object')

In [ ]:
exp_final.to_csv(origem+'exp_final.csv',index=False)