<a href="https://colab.research.google.com/github/JoseSergio414/Projeto-Integrador-II/blob/main/PROJETOII_dados_finais_exp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Cadeia Automotiva dados finais exportação

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive

In [ ]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
origem = '/content/drive/MyDrive/Data/COMEXSTAT/'

In [ ]:
arquivo_1 = origem + 'exp_final_I.csv'
arquivo_2 = origem + 'exp_final_II.csv'
arquivo_3 = origem + 'exp_final_III.csv'

In [ ]:
exp21_22 = pd.read_csv(arquivo_1,low_memory=False,sep=',',encoding='UTF-8')
exp23_24 = pd.read_csv(arquivo_2,low_memory=False,sep=',',encoding='UTF-8')
exp25_26 = pd.read_csv(arquivo_3,low_memory=False,sep=',',encoding='UTF-8')

In [ ]:
dado_exp_final = pd.concat([exp21_22,exp23_24,exp25_26], ignore_index=True)
dado_exp_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5811679 entries, 0 to 5811678
Data columns (total 11 columns):
 #   Column      Dtype
---  ------      -----
 0   CO_ANO      int64
 1   CO_MES      int64
 2   CO_PAIS     int64
 3   SG_UF_MUN   object
 4   CO_MUN      int64
 5   KG_LIQUIDO  int64
 6   VL_FOB      int64
 7   CO_SH4      int64
 8   NO_SH4_POR  object
 9   NO_MUN_MIN  object
 10  NO_PAIS     object
dtypes: int64(7), object(4)
memory usage: 487.7+ MB

In [ ]:
dado_exp_final.head(5)

,CO_ANO,CO_MES,CO_PAIS,SG_UF_MUN,CO_MUN,KG_LIQUIDO,VL_FOB,CO_SH4,NO_SH4_POR,NO_MUN_MIN,NO_PAIS,TOTAL EXPORTADO,TOTAL KGL EXP.
0,2021,3,493,SP,3434401,966,7788,3305,Preparações capilares,Osasco,México,7788,966
1,2021,7,386,SP,3409502,1,1544,8419,"Aparelhos e dispositivos, mesmo aquecidos elec...",Campinas,Itália,1544,1
2,2021,12,63,PR,4106902,73,907,8511,Aparelhos e dispositivos elétricos de ignição ...,Curitiba,Argentina,907,73
3,2021,7,586,SC,4202909,75,3942,6204,"Fatos de saia-casaco, conjuntos, casacos, vest...",Brusque,Paraguai,3942,75
4,2021,8,63,SP,3440002,6949,29604,8708,Partes e acessórios dos veículos automóveis da...,Pompéia,Argentina,29604,6949

In [ ]:
dado_exp_final.tail(5)

,CO_ANO,CO_MES,CO_PAIS,SG_UF_MUN,CO_MUN,KG_LIQUIDO,VL_FOB,CO_SH4,NO_SH4_POR,NO_MUN_MIN,NO_PAIS,TOTAL EXPORTADO,TOTAL KGL EXP.
5811674,2026,2,63,SP,3430607,35,4944,2849,Carbonetos de constituição química definida ou...,Mogi das Cruzes,Argentina,4944,35
5811675,2026,1,361,RS,4316808,518,41461,4813,"Papel para cigarros, mesmo cortado nas dimensõ...",Santa Cruz do Sul,Índia,41461,518
5811676,2026,1,63,RS,4302105,266,533,1902,"Massas alimentícias, mesmo cozidas ou recheada...",Bento Gonçalves,Argentina,533,266
5811677,2026,1,741,RJ,3304524,8,627,8907,Outras estruturas flutuantes (por exemplo: bal...,Rio das Ostras,Singapura,627,8
5811678,2026,2,580,RS,4309308,0,73,8541,"Díodos, transístores e dispositivos semelhante...",Guaíba,Panamá,73,0

In [ ]:
print(dado_exp_final.columns)

Index(['CO_ANO', 'CO_MES', 'CO_PAIS', 'SG_UF_MUN', 'CO_MUN', 'KG_LIQUIDO',
       'VL_FOB', 'CO_SH4', 'NO_SH4_POR', 'NO_MUN_MIN', 'NO_PAIS',
       'TOTAL EXPORTADO', 'TOTAL KGL EXP.'],
      dtype='object')

In [ ]:
dado_exp_final.to_csv(origem+'dado_exp_final.csv',index=False)