<a href="https://colab.research.google.com/github/JoseSergio414/Projeto-Integrador-II/blob/main/PROJETOII_exporta%C3%A7%C3%A3o_III.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Cadeia Automotiva exportação III parte

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive

In [ ]:
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
origem = '/content/drive/MyDrive/Data/COMEXSTAT/'

In [ ]:
arquivo_1 = origem + 'EXP_2025_MUN.csv'
arquivo_2 = origem + 'EXP_2026_MUN.csv'
pais = origem + 'PAIS.csv'
uf_mun =origem + 'UF_MUN.csv'
ncm_sh = origem + 'NCM_SH.csv'

In [ ]:
exp25 = pd.read_csv(arquivo_1,low_memory=False,sep=';',encoding='UTF-8')
exp26 = pd.read_csv(arquivo_2,low_memory=False,sep=';',encoding='UTF-8')
exppais = pd.read_csv(pais,low_memory=False,sep=';',encoding='latin1')
expufmun = pd.read_csv(uf_mun,low_memory=False,sep=';',encoding='latin1')
expsh = pd.read_csv(ncm_sh,low_memory=False,sep=';',encoding='latin1')

In [ ]:
exp_final = pd.concat([exp25,exp26], ignore_index=True)
exp_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1382846 entries, 0 to 1382845
Data columns (total 8 columns):
 #   Column      Non-Null Count    Dtype
---  ------      --------------    -----
 0   CO_ANO      1382846 non-null  int64
 1   CO_MES      1382846 non-null  int64
 2   SH4         1382846 non-null  int64
 3   CO_PAIS     1382846 non-null  int64
 4   SG_UF_MUN   1382846 non-null  object
 5   CO_MUN      1382846 non-null  int64
 6   KG_LIQUIDO  1382846 non-null  int64
 7   VL_FOB      1382846 non-null  int64
dtypes: int64(7), object(1)
memory usage: 84.4+ MB

In [ ]:
exp_final.head(5)

   CO_ANO  CO_MES   SH4  CO_PAIS SG_UF_MUN   CO_MUN  KG_LIQUIDO  VL_FOB
0    2025       9  7320      756        SP  3452205        8641  112533
1    2025      10  3306      467        SP  3448500          26     247
2    2025      10  7007      589        SP  3452205         229    2614
3    2025       6   701      476        ES  3205309         336     376
4    2025       7   707      445        BA  2927408          30      30

In [ ]:
exp_final.tail(5)

         CO_ANO  CO_MES   SH4  CO_PAIS SG_UF_MUN   CO_MUN  KG_LIQUIDO  VL_FOB
1382841    2026       2  2849       63        SP  3430607          35    4944
1382842    2026       1  4813      361        RS  4316808         518   41461
1382843    2026       1  1902       63        RS  4302105         266     533
1382844    2026       1  8907      741        RJ  3304524           8     627
1382845    2026       2  8541      580        RS  4309308           0      73

In [ ]:
exp_final = exp_final.merge(expsh[['CO_SH4','NO_SH4_POR']], left_on='SH4', right_on='CO_SH4', how='left')

In [ ]:
exp_final = exp_final.merge(expufmun[['CO_MUN_GEO','NO_MUN_MIN']],left_on='CO_MUN', right_on='CO_MUN_GEO', how='left')

In [ ]:
exp_final = exp_final.merge(exppais[['CO_PAIS','NO_PAIS']],on='CO_PAIS',how='left')

In [ ]:
exp_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10921782 entries, 0 to 10921781
Data columns (total 13 columns):
 #   Column      Dtype
---  ------      -----
 0   CO_ANO      int64
 1   CO_MES      int64
 2   SH4         int64
 3   CO_PAIS     int64
 4   SG_UF_MUN   object
 5   CO_MUN      int64
 6   KG_LIQUIDO  int64
 7   VL_FOB      int64
 8   CO_SH4      int64
 9   NO_SH4_POR  object
 10  CO_MUN_GEO  int64
 11  NO_MUN_MIN  object
 12  NO_PAIS     object
dtypes: int64(9), object(4)
memory usage: 1.1+ GB

In [ ]:
exp_final.head(5)

,CO_ANO,CO_MES,SH4,CO_PAIS,SG_UF_MUN,CO_MUN,KG_LIQUIDO,VL_FOB,CO_SH4,NO_SH4_POR,CO_MUN_GEO,NO_MUN_MIN,NO_PAIS
0,2025,9,7320,756,SP,3452205,8641,112533,7320,"Molas e folhas de molas, de ferro ou aço",3452205,Sorocaba,África do Sul
1,2025,9,7320,756,SP,3452205,8641,112533,7320,"Molas e folhas de molas, de ferro ou aço",3452205,Sorocaba,África do Sul
2,2025,9,7320,756,SP,3452205,8641,112533,7320,"Molas e folhas de molas, de ferro ou aço",3452205,Sorocaba,África do Sul
3,2025,10,3306,467,SP,3448500,26,247,3306,"Preparações para higiene bucal ou dentária, in...",3448500,Santos,Malta
4,2025,10,3306,467,SP,3448500,26,247,3306,"Preparações para higiene bucal ou dentária, in...",3448500,Santos,Malta

In [ ]:
exp_final.tail(5)

,CO_ANO,CO_MES,SH4,CO_PAIS,SG_UF_MUN,CO_MUN,KG_LIQUIDO,VL_FOB,CO_SH4,NO_SH4_POR,CO_MUN_GEO,NO_MUN_MIN,NO_PAIS
10921777,2026,2,8541,580,RS,4309308,0,73,8541,"Díodos, transístores e dispositivos semelhante...",4309308,Guaíba,Panamá
10921778,2026,2,8541,580,RS,4309308,0,73,8541,"Díodos, transístores e dispositivos semelhante...",4309308,Guaíba,Panamá
10921779,2026,2,8541,580,RS,4309308,0,73,8541,"Díodos, transístores e dispositivos semelhante...",4309308,Guaíba,Panamá
10921780,2026,2,8541,580,RS,4309308,0,73,8541,"Díodos, transístores e dispositivos semelhante...",4309308,Guaíba,Panamá
10921781,2026,2,8541,580,RS,4309308,0,73,8541,"Díodos, transístores e dispositivos semelhante...",4309308,Guaíba,Panamá

In [ ]:
exp_final = exp_final.drop('SH4', axis=1)

In [ ]:
exp_final = exp_final.drop('CO_MUN_GEO', axis=1)

In [ ]:
exp_final.head(5)

,CO_ANO,CO_MES,CO_PAIS,SG_UF_MUN,CO_MUN,KG_LIQUIDO,VL_FOB,CO_SH4,NO_SH4_POR,NO_MUN_MIN,NO_PAIS
0,2025,9,756,SP,3452205,8641,112533,7320,"Molas e folhas de molas, de ferro ou aço",Sorocaba,África do Sul
1,2025,9,756,SP,3452205,8641,112533,7320,"Molas e folhas de molas, de ferro ou aço",Sorocaba,África do Sul
2,2025,9,756,SP,3452205,8641,112533,7320,"Molas e folhas de molas, de ferro ou aço",Sorocaba,África do Sul
3,2025,10,467,SP,3448500,26,247,3306,"Preparações para higiene bucal ou dentária, in...",Santos,Malta
4,2025,10,467,SP,3448500,26,247,3306,"Preparações para higiene bucal ou dentária, in...",Santos,Malta

In [ ]:
print(f"Shape of exp_final before dropping duplicates: {exp_final.shape}")
exp_final = exp_final.drop_duplicates()
print(f"Shape of exp_final after dropping duplicates: {exp_final.shape}")

Shape of exp_final before dropping duplicates: (10921782, 11)
Shape of exp_final after dropping duplicates: (1382846, 11)

In [ ]:
exp_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1382846 entries, 0 to 10921768
Data columns (total 11 columns):
 #   Column      Non-Null Count    Dtype
---  ------      --------------    -----
 0   CO_ANO      1382846 non-null  int64
 1   CO_MES      1382846 non-null  int64
 2   CO_PAIS     1382846 non-null  int64
 3   SG_UF_MUN   1382846 non-null  object
 4   CO_MUN      1382846 non-null  int64
 5   KG_LIQUIDO  1382846 non-null  int64
 6   VL_FOB      1382846 non-null  int64
 7   CO_SH4      1382846 non-null  int64
 8   NO_SH4_POR  1382846 non-null  object
 9   NO_MUN_MIN  1382846 non-null  object
 10  NO_PAIS     1382846 non-null  object
dtypes: int64(7), object(4)
memory usage: 126.6+ MB

In [ ]:
print(exp_final.columns)

Index(['CO_ANO', 'CO_MES', 'CO_PAIS', 'SG_UF_MUN', 'CO_MUN', 'KG_LIQUIDO',
       'VL_FOB', 'CO_SH4', 'NO_SH4_POR', 'NO_MUN_MIN', 'NO_PAIS'],
      dtype='object')

In [ ]:
exp_final.to_csv(origem+'exp_final.csv',index=False)