<a href="https://colab.research.google.com/github/JoseSergio414/Projeto-Integrador-II/blob/main/PROJETOII_importa%C3%A7%C3%A3o_I.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Cadeia Automotiva importação I parte

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive

In [ ]:
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
origem = '/content/drive/MyDrive/Data/COMEXSTAT/'

In [ ]:
arquivo_1 = origem + 'IMP_2021_MUN.csv'
arquivo_2 = origem + 'IMP_2022_MUN.csv'
pais = origem + 'PAIS.csv'
uf_mun =origem + 'UF_MUN.csv'
ncm_sh = origem + 'NCM_SH.csv'

In [ ]:
imp21 = pd.read_csv(arquivo_1,low_memory=False,sep=';',encoding='UTF-8')
imp22 = pd.read_csv(arquivo_2,low_memory=False,sep=';',encoding='UTF-8')
imppais = pd.read_csv(pais,low_memory=False,sep=';',encoding='latin1')
impufmun = pd.read_csv(uf_mun,low_memory=False,sep=';',encoding='latin1')
impsh = pd.read_csv(ncm_sh,low_memory=False,sep=';',encoding='latin1')

In [ ]:
imp_final = pd.concat([imp21,imp22], ignore_index=True)
imp_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3134575 entries, 0 to 3134574
Data columns (total 8 columns):
 #   Column      Dtype
---  ------      -----
 0   CO_ANO      int64
 1   CO_MES      int64
 2   SH4         int64
 3   CO_PAIS     int64
 4   SG_UF_MUN   object
 5   CO_MUN      int64
 6   KG_LIQUIDO  int64
 7   VL_FOB      int64
dtypes: int64(7), object(1)
memory usage: 191.3+ MB

In [ ]:
imp_final.head(5)

   CO_ANO  CO_MES   SH4  CO_PAIS SG_UF_MUN   CO_MUN  KG_LIQUIDO   VL_FOB
0    2021       7  4115       23        SP  3416200        3668    11688
1    2021       4  8525      160        SP  3424709           1     3685
2    2021       7  8302      160        SP  3409205        5043    45918
3    2021       1  4009      249        SP  3420509       10417   207124
4    2021      11  8536      160        SP  3450308      306224  3298907

In [ ]:
imp_final.tail(5)

         CO_ANO  CO_MES   SH4  CO_PAIS SG_UF_MUN   CO_MUN  KG_LIQUIDO  VL_FOB
3134570    2022       1  3923      764        SP  3425904           0      13
3134571    2022       5  6804      383        SP  3456701           1     566
3134572    2022       3  2810      589        SP  3425102      140000  112787
3134573    2022       9  4811      160        SP  3448708        5380   25091
3134574    2022       7  8708      538        RS  4305108           6     517

In [ ]:
imp_final = imp_final.merge(impsh[['CO_SH4','NO_SH4_POR']], left_on='SH4', right_on='CO_SH4', how='left')

In [ ]:
imp_final = imp_final.merge(impufmun[['CO_MUN_GEO','NO_MUN_MIN']],left_on='CO_MUN', right_on='CO_MUN_GEO', how='left')

In [ ]:
imp_final = imp_final.merge(imppais[['CO_PAIS','NO_PAIS']],on='CO_PAIS',how='left')

In [ ]:
imp_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25992247 entries, 0 to 25992246
Data columns (total 13 columns):
 #   Column      Dtype
---  ------      -----
 0   CO_ANO      int64
 1   CO_MES      int64
 2   SH4         int64
 3   CO_PAIS     int64
 4   SG_UF_MUN   object
 5   CO_MUN      int64
 6   KG_LIQUIDO  int64
 7   VL_FOB      int64
 8   CO_SH4      int64
 9   NO_SH4_POR  object
 10  CO_MUN_GEO  int64
 11  NO_MUN_MIN  object
 12  NO_PAIS     object
dtypes: int64(9), object(4)
memory usage: 2.5+ GB

In [ ]:
imp_final.head(5)

,CO_ANO,CO_MES,SH4,CO_PAIS,SG_UF_MUN,CO_MUN,KG_LIQUIDO,VL_FOB,CO_SH4,NO_SH4_POR,CO_MUN_GEO,NO_MUN_MIN,NO_PAIS
0,2021,7,4115,23,SP,3416200,3668,11688,4115,Couro reconstituído à base de couro ou de fibr...,3416200,Franca,Alemanha
1,2021,7,4115,23,SP,3416200,3668,11688,4115,Couro reconstituído à base de couro ou de fibr...,3416200,Franca,Alemanha
2,2021,4,8525,160,SP,3424709,1,3685,8525,Aparelhos emissores (transmissores) para radio...,3424709,Jaguariúna,China
3,2021,4,8525,160,SP,3424709,1,3685,8525,Aparelhos emissores (transmissores) para radio...,3424709,Jaguariúna,China
4,2021,4,8525,160,SP,3424709,1,3685,8525,Aparelhos emissores (transmissores) para radio...,3424709,Jaguariúna,China

In [ ]:
imp_final.tail(5)

,CO_ANO,CO_MES,SH4,CO_PAIS,SG_UF_MUN,CO_MUN,KG_LIQUIDO,VL_FOB,CO_SH4,NO_SH4_POR,CO_MUN_GEO,NO_MUN_MIN,NO_PAIS
25992242,2022,7,8708,538,RS,4305108,6,517,8708,Partes e acessórios dos veículos automóveis da...,4305108,Caxias do Sul,Noruega
25992243,2022,7,8708,538,RS,4305108,6,517,8708,Partes e acessórios dos veículos automóveis da...,4305108,Caxias do Sul,Noruega
25992244,2022,7,8708,538,RS,4305108,6,517,8708,Partes e acessórios dos veículos automóveis da...,4305108,Caxias do Sul,Noruega
25992245,2022,7,8708,538,RS,4305108,6,517,8708,Partes e acessórios dos veículos automóveis da...,4305108,Caxias do Sul,Noruega
25992246,2022,7,8708,538,RS,4305108,6,517,8708,Partes e acessórios dos veículos automóveis da...,4305108,Caxias do Sul,Noruega

In [ ]:
imp_final = imp_final.drop('SH4', axis=1)

In [ ]:
imp_final = imp_final.drop('CO_MUN_GEO', axis=1)

In [ ]:
imp_final.head(5)

,CO_ANO,CO_MES,CO_PAIS,SG_UF_MUN,CO_MUN,KG_LIQUIDO,VL_FOB,CO_SH4,NO_SH4_POR,NO_MUN_MIN,NO_PAIS
0,2021,7,23,SP,3416200,3668,11688,4115,Couro reconstituído à base de couro ou de fibr...,Franca,Alemanha
1,2021,7,23,SP,3416200,3668,11688,4115,Couro reconstituído à base de couro ou de fibr...,Franca,Alemanha
2,2021,4,160,SP,3424709,1,3685,8525,Aparelhos emissores (transmissores) para radio...,Jaguariúna,China
3,2021,4,160,SP,3424709,1,3685,8525,Aparelhos emissores (transmissores) para radio...,Jaguariúna,China
4,2021,4,160,SP,3424709,1,3685,8525,Aparelhos emissores (transmissores) para radio...,Jaguariúna,China

In [ ]:
print(f"Shape of imp_final before dropping duplicates: {imp_final.shape}")
imp_final = imp_final.drop_duplicates()
print(f"Shape of imp_final after dropping duplicates: {imp_final.shape}")

Shape of imp_final before dropping duplicates: (25992247, 11)
Shape of imp_final after dropping duplicates: (3134575, 11)

In [ ]:
imp_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3134575 entries, 0 to 25992229
Data columns (total 11 columns):
 #   Column      Dtype
---  ------      -----
 0   CO_ANO      int64
 1   CO_MES      int64
 2   CO_PAIS     int64
 3   SG_UF_MUN   object
 4   CO_MUN      int64
 5   KG_LIQUIDO  int64
 6   VL_FOB      int64
 7   CO_SH4      int64
 8   NO_SH4_POR  object
 9   NO_MUN_MIN  object
 10  NO_PAIS     object
dtypes: int64(7), object(4)
memory usage: 287.0+ MB

In [ ]:
print(imp_final.columns)

Index(['CO_ANO', 'CO_MES', 'CO_PAIS', 'SG_UF_MUN', 'CO_MUN', 'KG_LIQUIDO',
       'VL_FOB', 'CO_SH4', 'NO_SH4_POR', 'NO_MUN_MIN', 'NO_PAIS'],
      dtype='object')

In [ ]:
imp_final.to_csv(origem+'imp_final.csv',index=False)